version: '3.8'

services:
  postgres:
    image: postgres
    container_name: postgres_container
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - C:/Users/ASUS/Desktop/Backend Springboot learning/db/pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_container
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - C:/Users/ASUS/Desktop/Backend Springboot learning/db/pgadmin:/var/lib/pgadmin
    ports:
      - "80:80"
    depends_on:
      - postgres